"""Compute DeBERTa-base parity values for the paper (items A-K).

Writes outputs/DEBERTA_PAPER_PARITY.md and a few helper CSVs.

Usage:
    .venv/bin/python scripts/deberta_paper_parity.py
"""
from __future__ import annotations

import json
import sys
from collections import Counter
from pathlib import Path

import numpy as np
import pandas as pd
from scipy.stats import mannwhitneyu
from sklearn.metrics import average_precision_score

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "outputs"
BASIL = OUT / "basil"
BSHAP = OUT / "basil_shap"

REPORT = OUT / "DEBERTA_PAPER_PARITY.md"

sys.path.insert(0, str(ROOT))
from babe_fig6_confound import (  # type: ignore
    CATEGORIES,
    aggregate_words,
    categorize_word,
    category_proportions,
    normalize_word,
)


def load_jsonl(p):
    return [json.loads(l) for l in open(p, "r", encoding="utf-8")]


def mean_abs(rec):
    wa = rec["word_attribs"]
    return float(np.mean([abs(x["shap"]) for x in wa])) if wa else 0.0


def max_abs(rec):
    wa = rec["word_attribs"]
    return float(np.max([abs(x["shap"]) for x in wa])) if wa else 0.0


def sum_abs(rec):
    wa = rec["word_attribs"]
    return float(np.sum([abs(x["shap"]) for x in wa])) if wa else 0.0


def cat(rec):
    g, p = int(rec["gold"]), int(rec["pred"])
    if g == 1 and p == 1: return "TP"
    if g == 0 and p == 1: return "FP"
    if g == 0 and p == 0: return "TN"
    return "FN"


# ----------------------------------------------------------------------------
# Load all caches
print("Loading caches ...")
babe_db = load_jsonl(OUT / "shap_samples_deberta.jsonl")
babe_bd = load_jsonl(OUT / "shap_samples.jsonl")
babe_dr = load_jsonl(OUT / "shap_samples_daroberta.jsonl")
basil_db = load_jsonl(BSHAP / "samples_deberta.jsonl")
basil_bd = load_jsonl(BSHAP / "samples_biasdetector.jsonl")
basil_dr = load_jsonl(BSHAP / "samples_daroberta.jsonl")

basil_master = pd.read_csv(ROOT / "basil_sentences.csv")
pred_db = pd.read_csv(BASIL / "predictions_deberta.csv")
pred_bd = pd.read_csv(BASIL / "predictions_biasdetector.csv")
pred_dr = pd.read_csv(BASIL / "predictions_daroberta.csv")

# Build merged BASIL frame: master joined with prob/pred for all 3 models
merged = basil_master.copy()
for suffix, pf in (("deberta", pred_db), ("biasdetector", pred_bd), ("daroberta", pred_dr)):
    pf2 = pf.rename(columns={"prob_biased": f"prob_{suffix}", "pred": f"pred_{suffix}"})
    merged = merged.merge(pf2, on=["triplet_uuid", "outlet_idx", "sentence_idx"], how="left")

print(f"  babe deberta: {len(babe_db)} records")
print(f"  basil deberta: {len(basil_db)} records")
print(f"  merged BASIL: {len(merged)} rows")

report = []
report.append("# DeBERTa-base — Paper-Parity Analysis\n")
report.append("Generated by `scripts/deberta_paper_parity.py`. See section "
              "letters keyed to the user's consolidated prompt.\n")

# ============================================================================
# K. Sanity check — per-sentence sum of |SHAP| on 5 random TPs per model
# Do this FIRST since the answer determines how to interpret the rest.
# ============================================================================
report.append("## K. Sanity check — is the 5-10× magnitude gap real?\n")
report.append("Per-sentence sum and mean of |SHAP| over `word_attribs` for "
              "5 BABE-TP sentences per model (seed=7). If DeBERTa's *sums* "
              "are 5-10× larger too, the gap is genuine sparse-attribution "
              "behavior; if only the *means* are large (sums comparable), "
              "the gap is a SHAP normalization artifact.\n")

rng = np.random.default_rng(7)
def tp_recs(recs):
    return [r for r in recs if int(r["gold"]) == 1 and int(r["pred"]) == 1]
sanity_rows = []
for model_name, recs in [("bias-detector", babe_bd), ("DA-RoBERTa", babe_dr), ("DeBERTa-base", babe_db)]:
    tps = tp_recs(recs)
    picks = rng.choice(len(tps), size=5, replace=False)
    for i, idx in enumerate(picks):
        r = tps[idx]
        sanity_rows.append({
            "model": model_name,
            "i": i,
            "n_words": len(r["word_attribs"]),
            "sum_|SHAP|": sum_abs(r),
            "mean_|SHAP|": mean_abs(r),
            "max_|SHAP|": max_abs(r),
        })
sanity = pd.DataFrame(sanity_rows)
report.append(sanity.to_markdown(index=False, floatfmt=".4f") + "\n")

agg = sanity.groupby("model").agg(
    n_words_mean=("n_words", "mean"),
    sum_mean=("sum_|SHAP|", "mean"),
    mean_mean=("mean_|SHAP|", "mean"),
).round(4)
report.append("\n**Aggregated by model (5 random BABE-TP samples each):**\n")
report.append(agg.to_markdown(floatfmt=".4f") + "\n")

# Compute ratios across all TPs (not just the 5) for the headline
def all_tp_stats(recs):
    tps = tp_recs(recs)
    return {
        "n": len(tps),
        "median_sum": float(np.median([sum_abs(r) for r in tps])),
        "median_mean": float(np.median([mean_abs(r) for r in tps])),
        "median_n_words": float(np.median([len(r["word_attribs"]) for r in tps])),
    }
stats = {n: all_tp_stats(r) for n, r in [
    ("bias-detector", babe_bd), ("DA-RoBERTa", babe_dr), ("DeBERTa-base", babe_db),
]}
report.append("\n**Population-level (all BABE TPs):**\n")
pop_df = pd.DataFrame(stats).T
report.append(pop_df.to_markdown(floatfmt=".4f") + "\n")

db = stats["DeBERTa-base"]
bd_ref = stats["bias-detector"]
sum_ratio  = db["median_sum"]  / bd_ref["median_sum"]
mean_ratio = db["median_mean"] / bd_ref["median_mean"]
nwords_ratio = db["median_n_words"] / bd_ref["median_n_words"]
report.append(f"\n**Ratios vs bias-detector (population median):** "
              f"sum={sum_ratio:.2f}×, mean={mean_ratio:.2f}×, "
              f"n_words={nwords_ratio:.2f}×\n")
if sum_ratio > 3.0:
    report.append("\n**Verdict:** sum of |SHAP| is >3× bias-detector's "
                  "→ the magnitude gap is GENUINE (sparse-but-large attribution), "
                  "not a normalization artifact.\n")
elif mean_ratio > 3.0 and sum_ratio < 1.5:
    report.append("\n**Verdict:** sums are comparable but per-instance mean is "
                  "inflated by smaller n_words → likely word-aggregation bug. "
                  "Re-run `scripts/fix_deberta_word_aggregation.py`.\n")
else:
    report.append("\n**Verdict:** sums, means, and n_words are all comparable to "
                  "bias-detector — no magnitude gap, no aggregation bug. "
                  "DeBERTa-base sits in the same calibration range as the other "
                  "models on the per-instance |SHAP| scale.\n")

# ============================================================================
# A. BASIL-full performance: FPR, AUPRC for DeBERTa
# ============================================================================
report.append("\n## A. BASIL-full performance for DeBERTa\n")
# BASIL "full" view = all 7984 rows
y_true = merged["biased"].astype(int).values
y_pred = merged["pred_deberta"].astype(int).values
y_prob = merged["prob_deberta"].astype(float).values
fp = int(((y_true == 0) & (y_pred == 1)).sum())
tn = int(((y_true == 0) & (y_pred == 0)).sum())
fpr_basil_db = fp / (fp + tn)
auprc_basil_db = average_precision_score(y_true, y_prob)
basil_baseline = y_true.mean()
basil_lift_db = auprc_basil_db / basil_baseline

# Same for BABE-test for context (227 sampled, but we have the full 1000-sentence test)
# Use shap cache to get confusion — actually use predictions from saved jsonl
def babe_confusion(recs):
    tp = sum(1 for r in recs if int(r["gold"]) == 1 and int(r["pred"]) == 1)
    fp_ = sum(1 for r in recs if int(r["gold"]) == 0 and int(r["pred"]) == 1)
    tn_ = sum(1 for r in recs if int(r["gold"]) == 0 and int(r["pred"]) == 0)
    fn_ = sum(1 for r in recs if int(r["gold"]) == 1 and int(r["pred"]) == 0)
    return tp, fp_, tn_, fn_
# But the BABE cache has only sampled instances — for FPR we need full counts.
# Use the original BABE confusion already computed at training time:
# DeBERTa: TP=421, FP=27, TN=414, FN=138 (test set 1000)
babe_db_fpr = 27 / (27 + 414)
report.append(f"- BABE-test FPR: 27/(27+414) = **{babe_db_fpr:.4f}**\n")
report.append(f"- BABE-test AUPRC: **0.9483** (from training-time eval on full test split)\n")
report.append(f"- BASIL-full FPR (threshold 0.5): {fp}/({fp}+{tn}) = **{fpr_basil_db:.4f}**\n")
report.append(f"- BASIL-full AUPRC (threshold-free): **{auprc_basil_db:.4f}**\n")
report.append(f"- BASIL-full AUPRC baseline (prior): {basil_baseline:.4f} → lift × **{basil_lift_db:.2f}**\n")

# ============================================================================
# B/C. Median per-instance mean/max |SHAP| for DeBERTa × {BABE,BASIL} × {TP,FP,TN,FN}
# ============================================================================
report.append("\n## B. Median per-instance mean |SHAP| — DeBERTa × corpus × category\n")
mag_rows = []
for corpus, recs in [("BABE", babe_db), ("BASIL", basil_db)]:
    by_cat = {"TP": [], "FP": [], "TN": [], "FN": []}
    for r in recs:
        by_cat[cat(r)].append(r)
    for c in ["TP", "FP", "TN", "FN"]:
        ms = [mean_abs(r) for r in by_cat[c]]
        mag_rows.append({
            "corpus": corpus, "category": c, "n": len(ms),
            "median_mean_|SHAP|": float(np.median(ms)) if ms else float("nan"),
            "mean_mean_|SHAP|":   float(np.mean(ms)) if ms else float("nan"),
        })
mag_df = pd.DataFrame(mag_rows)
report.append(mag_df.to_markdown(index=False, floatfmt=".4f") + "\n")

# Compare across models for context on TN (the key calibration cell)
report.append("\n**Cross-model TN comparison (median per-instance mean |SHAP|):**\n")
tn_rows = []
for corpus_name, recs_by_model in [
    ("BABE", [("bd", babe_bd), ("dr", babe_dr), ("deberta", babe_db)]),
    ("BASIL", [("bd", basil_bd), ("dr", basil_dr), ("deberta", basil_db)]),
]:
    row = {"corpus": corpus_name}
    for label, recs in recs_by_model:
        tns = [mean_abs(r) for r in recs if cat(r) == "TN"]
        row[f"{label} TN"] = float(np.median(tns)) if tns else float("nan")
    tn_rows.append(row)
report.append(pd.DataFrame(tn_rows).to_markdown(index=False, floatfmt=".4f") + "\n")

# C. Median max |SHAP|
report.append("\n## C. Median per-instance max |SHAP| — DeBERTa × corpus × category\n")
max_rows = []
for corpus, recs in [("BABE", babe_db), ("BASIL", basil_db)]:
    by_cat = {"TP": [], "FP": [], "TN": [], "FN": []}
    for r in recs:
        by_cat[cat(r)].append(r)
    for c in ["TP", "FP", "TN", "FN"]:
        ms = [max_abs(r) for r in by_cat[c]]
        max_rows.append({
            "corpus": corpus, "category": c, "n": len(ms),
            "median_max_|SHAP|": float(np.median(ms)) if ms else float("nan"),
        })
report.append(pd.DataFrame(max_rows).to_markdown(index=False, floatfmt=".4f") + "\n")

# ============================================================================
# D. Top 10 bias indicators by mean |SHAP| on BABE
# ============================================================================
report.append("\n## D. Top 10 BABE bias indicators for DeBERTa\n")
gwi = pd.read_csv(OUT / "global_word_importance_deberta.csv")
# global_word_importance_deberta.csv has all words including spurious all-concatenated
# strings (e.g. "thegruesomethree" with count=1). Filter to count >= 3 for stability.
top_stable = (gwi[gwi["count"] >= 3]
              .nlargest(10, "mean_abs_shap")
              [["word", "mean_abs_shap", "mean_shap", "count"]])
report.append("Filtered to words with count ≥ 3 (drops one-off concatenated tokens "
              "from SHAP's word-boundary aggregation):\n")
report.append(top_stable.to_markdown(index=False, floatfmt=".4f") + "\n")

# Unfiltered top 10 for transparency
report.append("\nUnfiltered top 10 (includes count=1 single-occurrence words; "
              "less reliable):\n")
top_all = gwi.nlargest(10, "mean_abs_shap")[["word", "mean_abs_shap", "mean_shap", "count"]]
report.append(top_all.to_markdown(index=False, floatfmt=".4f") + "\n")

# ============================================================================
# E. Matched-pool TP-vs-FP category composition on BABE (p75 threshold)
# Threshold computed over the pooled (3 models × TP+FP) mean_abs_shap distribution.
# ============================================================================
report.append("\n## E. Matched-pool TP-vs-FP category composition (BABE, p75)\n")

def by_pred_class(recs):
    out = {"TP": [], "FP": []}
    for r in recs:
        c = cat(r)
        if c in out:
            out[c].append(r)
    return out

by_model = {
    "bias-detector": by_pred_class(babe_bd),
    "DA-RoBERTa":    by_pred_class(babe_dr),
    "DeBERTa-base":  by_pred_class(babe_db),
}

# Pooled p75 threshold over all (model, pred_class, word) mean_abs_shap
pooled = []
for model, by_pc in by_model.items():
    for pc in ["TP", "FP"]:
        agg = aggregate_words(by_pc[pc])
        pooled.extend(agg["mean_abs_shap"].tolist())
p75 = float(np.percentile(pooled, 75))
report.append(f"Pooled p75 threshold (3 models × {{TP,FP}}, n_words = {len(pooled)}): "
              f"**{p75:.4f}**\n")

rows = []
for model, by_pc in by_model.items():
    for pc in ["TP", "FP"]:
        agg = aggregate_words(by_pc[pc])
        top = agg[agg["mean_abs_shap"] >= p75]
        props = category_proportions(top)
        rows.append({
            "model": model, "pred_class": pc, "n_selected": len(top),
            **{c: props[c] for c in CATEGORIES}
        })
cat_df = pd.DataFrame(rows)
report.append(cat_df.to_markdown(index=False, floatfmt=".1f") + "\n")
report.append("\nDeBERTa-base specifically:\n")
deb_only = cat_df[cat_df.model == "DeBERTa-base"]
report.append(deb_only.to_markdown(index=False, floatfmt=".1f") + "\n")

# ============================================================================
# F. Mann-Whitney U tests
# ============================================================================
report.append("\n## F. Mann-Whitney U tests (per-instance mean |SHAP|)\n")

def shap_by_cat(recs, c):
    return np.array([mean_abs(r) for r in recs if cat(r) == c])

def mw(a, b, label):
    a = np.asarray(a, dtype=float); b = np.asarray(b, dtype=float)
    if len(a) < 2 or len(b) < 2:
        return {"test": label, "n1": len(a), "n2": len(b), "U": float("nan"),
                "p": float("nan"), "|r|": float("nan")}
    res = mannwhitneyu(a, b, alternative="two-sided")
    U = float(res.statistic); p = float(res.pvalue)
    r = abs(1.0 - 2.0 * U / (len(a) * len(b)))
    return {"test": label, "n1": len(a), "n2": len(b), "U": U, "p": p, "|r|": r}

mw_rows = []
mw_rows.append(mw(shap_by_cat(babe_db, "TP"),  shap_by_cat(babe_db, "FP"),
                  "DeBERTa BABE: TP vs FP"))
mw_rows.append(mw(shap_by_cat(basil_db, "TP"), shap_by_cat(basil_db, "FP"),
                  "DeBERTa BASIL: TP vs FP"))
mw_rows.append(mw(shap_by_cat(babe_bd, "TN"),  shap_by_cat(babe_db, "TN"),
                  "BABE TN: BD vs DeBERTa"))
mw_rows.append(mw(shap_by_cat(babe_dr, "TN"),  shap_by_cat(babe_db, "TN"),
                  "BABE TN: DR vs DeBERTa"))
mw_rows.append(mw(shap_by_cat(basil_bd, "TN"), shap_by_cat(basil_db, "TN"),
                  "BASIL TN: BD vs DeBERTa"))
mw_rows.append(mw(shap_by_cat(basil_dr, "TN"), shap_by_cat(basil_db, "TN"),
                  "BASIL TN: DR vs DeBERTa"))
report.append(pd.DataFrame(mw_rows).to_markdown(index=False,
              floatfmt=("", "", "", ".1f", ".2e", ".3f")) + "\n")

# ============================================================================
# G. Bias-type independence on BASIL @ 0.3 for DeBERTa
# ============================================================================
report.append("\n## G. Bias-type independence on BASIL @ threshold 0.3 (DeBERTa)\n")

THR = 0.3
db_pred_thr = (merged["prob_deberta"] >= THR).astype(int)
def recall_on(mask):
    pos = merged[mask & (merged["biased"] == 1)]
    if len(pos) == 0:
        return float("nan"), 0
    n_pos = len(pos)
    n_hit = int((db_pred_thr.loc[pos.index] == 1).sum())
    return n_hit / n_pos, n_pos

lex_mask = (merged["has_lex"] == 1) & (merged["has_inf"] == 0)
inf_mask = (merged["has_inf"] == 1) & (merged["has_lex"] == 0)
both_mask = merged["has_both_types"] == 1

R_lex,  n_lex  = recall_on(lex_mask)
R_inf,  n_inf  = recall_on(inf_mask)
R_both, n_both = recall_on(both_mask)
P_both_pred = 1.0 - (1.0 - R_lex) * (1.0 - R_inf)

bti = pd.DataFrame([
    {"slice": "lex-only", "n_pos": n_lex,  "recall_@_0.3": R_lex},
    {"slice": "inf-only", "n_pos": n_inf,  "recall_@_0.3": R_inf},
    {"slice": "both-types", "n_pos": n_both, "recall_@_0.3": R_both},
])
report.append(bti.to_markdown(index=False, floatfmt=".4f") + "\n")
report.append(f"\nIndependence prediction: "
              f"P(both)_predicted = 1 − (1 − R_lex)(1 − R_inf) = "
              f"**{P_both_pred:.4f}**\n")
report.append(f"Observed R(both) = **{R_both:.4f}**\n")
report.append(f"Gap (observed − predicted) = **{R_both - P_both_pred:+.4f}** "
              f"({'sub-additive' if R_both < P_both_pred else 'super-additive'})\n")

# ============================================================================
# H. AUPRC across 6 BASIL strata + lifts
# ============================================================================
report.append("\n## H. DeBERTa AUPRC across BASIL strata\n")
# Mirror view_filters from basil_eval.py
def basil_views(df):
    return [
        ("full",           pd.Series(True, index=df.index)),
        ("lex-only",       (df.biased == 0) | ((df.has_lex == 1) & (df.has_inf == 0))),
        ("inf-only",       (df.biased == 0) | ((df.has_inf == 1) & (df.has_lex == 0))),
        ("both-types",     (df.biased == 0) | (df.has_both_types == 1)),
        ("quote-excluded", (df.biased == 0) | (df.quote_status.isin(["no_quote", "mixed"]))),
        ("quote-only",     (df.biased == 0) | (df.quote_status == "all_in_quote")),
    ]
strata_rows = []
for view, mask in basil_views(merged):
    sub = merged[mask]
    y = sub["biased"].astype(int).values
    p = sub["prob_deberta"].astype(float).values
    base = y.mean() if len(y) else float("nan")
    if y.sum() == 0 or (y == 0).sum() == 0:
        au = float("nan"); lift = float("nan")
    else:
        au = float(average_precision_score(y, p))
        lift = au / base
    strata_rows.append({
        "view": view, "n": len(sub), "pos_rate": base,
        "AUPRC": au, "lift": lift,
    })
report.append(pd.DataFrame(strata_rows).to_markdown(index=False, floatfmt=".4f") + "\n")

# ============================================================================
# I. DeBERTa FP vocabulary size on BABE
# ============================================================================
report.append("\n## I. DeBERTa FP vocabulary on BABE\n")
fp_recs_db = [r for r in babe_db if cat(r) == "FP"]
db_fp_vocab = set()
for r in fp_recs_db:
    for wa in r["word_attribs"]:
        w = normalize_word(wa["word"])
        if w:
            db_fp_vocab.add(w)
# Also compute under the p75 threshold filter to match the existing Table 5 style
agg_db_fp = aggregate_words(fp_recs_db)
db_fp_vocab_p75 = set(agg_db_fp[agg_db_fp["mean_abs_shap"] >= p75]["word"])

# Same for BD and DR for comparison
def fp_vocab_p75(recs):
    fp_r = [r for r in recs if cat(r) == "FP"]
    agg = aggregate_words(fp_r)
    return len(agg), len(agg[agg["mean_abs_shap"] >= p75])

bd_all, bd_p75 = fp_vocab_p75(babe_bd)
dr_all, dr_p75 = fp_vocab_p75(babe_dr)

vocab_tbl = pd.DataFrame([
    {"model": "bias-detector", "FP_vocab_all": bd_all, "FP_vocab_p75": bd_p75},
    {"model": "DA-RoBERTa",    "FP_vocab_all": dr_all, "FP_vocab_p75": dr_p75},
    {"model": "DeBERTa-base",  "FP_vocab_all": len(agg_db_fp), "FP_vocab_p75": len(db_fp_vocab_p75)},
])
report.append(vocab_tbl.to_markdown(index=False) + "\n")
report.append(f"\n(For reference: the paper Table 5 shows BD=660, DR=249 at "
              f"the p75 filter — those numbers come from a different stratum "
              f"or threshold definition than what's recomputable from the "
              f"current caches. The numbers above are computed with the same "
              f"matched p75 pool used in section E.)\n")

# ============================================================================
# J. Pairwise BASIL FP overlap (DeBERTa vs BD, DeBERTa vs DR)
# ============================================================================
report.append("\n## J. Pairwise BASIL FP overlap (DeBERTa vs BD, DeBERTa vs DR)\n")
neg = merged[merged["biased"] == 0]
fp_bd_keys = set(neg.loc[neg["pred_biasdetector"] == 1].index)
fp_dr_keys = set(neg.loc[neg["pred_daroberta"] == 1].index)
fp_db_keys = set(neg.loc[neg["pred_deberta"] == 1].index)
n_neg = len(neg)

def overlap(a, b, label_a, label_b):
    inter = len(a & b)
    union = len(a | b)
    p_a = len(a) / n_neg
    p_b = len(b) / n_neg
    expected_under_indep = p_a * p_b * n_neg
    return {
        "pair": f"{label_a} ∩ {label_b}",
        f"|{label_a}|": len(a),
        f"|{label_b}|": len(b),
        "observed_∩": inter,
        "expected_indep": round(expected_under_indep, 2),
        "ratio_obs/exp": round(inter / expected_under_indep, 2) if expected_under_indep else float("nan"),
        "Jaccard": round(inter / union, 4) if union else float("nan"),
    }

ov_rows = [
    overlap(fp_db_keys, fp_bd_keys, "DeBERTa", "BD"),
    overlap(fp_db_keys, fp_dr_keys, "DeBERTa", "DR"),
    overlap(fp_bd_keys, fp_dr_keys, "BD", "DR"),  # baseline pair from existing analysis
]
report.append(pd.DataFrame(ov_rows).to_markdown(index=False) + "\n")
triple = fp_bd_keys & fp_dr_keys & fp_db_keys
report.append(f"\nTriple FP intersection (all 3 models): **{len(triple)} sentences** "
              f"(out of {n_neg} BASIL negatives)\n")

# ============================================================================
# Final write
# ============================================================================
REPORT.write_text("\n".join(report), encoding="utf-8")
print(f"\nWrote {REPORT}")
